campos_persona = [
    'id',
    # 'create_date',
    'x_institute_career',
    'x_institution_type_ID',
    'x_level_ID',
    'x_state_ID',
    'x_user_type_ID',
    # 'x_performances',
    # 'x_registry',
    'x_cpnaa_enrollment_state',
    'x_name',
    'x_partner_ID',
    'x_grade_date',
    'x_expedition_country',
    'x_expedition_state',
    'x_celphone',
    # 'x_linkedin',
    # 'x_foreign_state',
    'x_gender_ID',
    'x_phone',
    'x_email',
    'x_local_phone',
    # 'x_professional_experience',
    'x_address',
    'x_document',
    # 'x_folder',
    'x_city_ID',
    'x_country_ID',
    'x_document_type_ID',
    'x_professional_registration_ID',
    # 'x_certification_studies_completed',
    # 'x_min_convalidation',
    'x_expedition_city',
    'x_institution_ID',
    'x_last_name',
    'x_tramite',
    # 'x_certification_vigencia',
    # 'x_address_char',
    # 'x_phone_char',
    # 'x_is_working',
    # 'x_company',
    # 'x_position',
    # 'x_phone_char_2',
    # 'x_birthdate',
    # 'x_characterization',
    # 'x_email_char',
    # 'x_email_char_2',
    'x_user_image',
    # 'x_profession',
    'x_fecha_resolucion_fallecido',
    'x_resolucion_fallecido',
    'x_fallecido'
]